### ISSUE TITLE
Create a class to center elements

### ISSUE THREAD

**Issue by sanatankc** [itsjzt/utility-CSS#3]

**Comment by sanatankc** [comment]
There should be a class to center elements easily.

Something like this
```html
<div class='-center'>
    <!-- Children Elements -->
</div>
```

**Comment by itsjzt** [comment]
Actually, I also wanted to make a class for that but as it is can easily get by flexbox, I need to implement flexbox first. I'm working on flexbox and grid.

**Comment by itsjzt** [comment]
can you help me doing that

**Comment by sanatankc** [comment]
ofcourse. 👍

**Comment by sanatankc** [comment]
where should I start now

**Comment by itsjzt** [comment]
I will get you in PM

**Comment by itsjzt** [comment]
Now we have implemeted it in dev, so now I think I can close this
